// Generated by CoffeeScript 1.9.2
var BinarySearchTree;

BinarySearchTree = (function() {
  var nullNode;

  function BinarySearchTree(root, nullNode) {
    this.root = root;
  }

  nullNode = {
    depth: 0
  };

  BinarySearchTree.prototype.insert = function(val) {
    var current, node, results;
    node = {
      val: val,
      left: nullNode,
      right: nullNode
    };
    if (this.root) {
      current = this.root;
      results = [];
      while (!(current.left === node || current.right === node)) {
        if (val === current.val) {
          break;
        } else if (val < current.val) {
          if (current.left === nullNode) {
            results.push(current.left = node);
          } else {
            results.push(current = current.left);
          }
        } else {
          if (current.right === nullNode) {
            results.push(current.right = node);
          } else {
            results.push(current = current.right);
          }
        }
      }
      return results;
    } else {
      return this.root = node;
    }
  };

  BinarySearchTree.prototype.contains = function(val) {
    var contain, node, traverse;
    node = this.root;
    contain = false;
    traverse = function(node, val) {
      var current;
      current = node;
      if (current.val === val) {
        return contain = true;
      } else {
        if (current.left !== nullNode) {
          traverse(current.left, val);
        }
        if (current.right !== nullNode) {
          traverse(current.right, val);
        }
        return contain;
      }
    };
    return traverse(node, val);
  };

  BinarySearchTree.prototype.size = function() {
    var count, node, traverse;
    if (this.root == null) {
      return 0;
    }
    node = this.root;
    count = 0;
    traverse = function(node) {
      var current;
      current = node;
      count += 1;
      if (current.left !== nullNode) {
        traverse(current.left);
      }
      if (current.right !== nullNode) {
        traverse(current.right);
      }
      return count;
    };
    return traverse(node);
  };

  BinarySearchTree.prototype.depth = function() {
    var traverse;
    traverse = function(node) {
      var leftDepth, rightDepth;
      if (node === nullNode) {
        return 0;
      }
      leftDepth = traverse(node.left);
      rightDepth = traverse(node.right);
      if (leftDepth > rightDepth) {
        return leftDepth + 1;
      } else {
        return rightDepth + 1;
      }
    };
    return traverse(this.root);
  };

  BinarySearchTree.prototype.balanced = function() {
    var count, leftSide, rightSide, traverse;
    if (this.root == null) {
      return 0;
    }
    traverse = function(node) {
      var current;
      current = node;
      count += 1;
      if (current.left !== nullNode) {
        traverse(current.left);
      }
      if (current.right !== nullNode) {
        traverse(current.right);
      }
      return count;
    };
    count = 0;
    leftSide = traverse(this.root.left);
    count = 0;
    rightSide = traverse(this.root.right);
    return leftSide - rightSide;
  };

  return BinarySearchTree;

})();

module.exports = BinarySearchTree;
