// Generated by CoffeeScript 1.9.1
var Stack;

Stack = (function() {
  function Stack(head) {
    this.head = head;
  }

  Stack.prototype.push = function(val) {
    var node;
    node = {
      val: val,
      nxt: null
    };
    if (this.head != null) {
      node = {
        val: val,
        nxt: this.head
      };
      return this.head = node;
    } else {
      return this.head = node;
    }
  };

  Stack.prototype.pop = function() {
    var temp;
    if (this.head == null) {
      throw new Error("no stack exists");
    }
    temp = this.head.val;
    this.head = this.head.nxt;
    return temp;
  };

  return Stack;

})();

module.exports = Stack;
